#!/bin/bash
# A simple for loop example

for item in "apple" "banana" "cherry"
do
    echo "Fruit: $item"
done
---------------------------- 

#!/bin/bash
# A simple while loop example

count=5
while [ $count -gt 0 ]
do
    echo "Countdown: $count"
    ((count--))
    #let count-- 
done
echo "Liftoff!"


-------------------------------------------------------

#!/bin/bash
# A case statement to match a variable

read -p "Enter a number between 1 and 3: " number

case $number in
    1)
        echo "You entered One"
        ;;
    2)
        echo "You entered Two"
        ;;
    3)
        echo "You entered Three"
        ;;
    *)
        echo "Invalid number! Please enter between 1 and 3."
        ;;
esac


-----------------------------------------------------------------------------------------

#!/bin/bash
# A function to add two numbers


add_numbers() {
    local num1=$1
    local num2=$2
    local sum=$((num1 + num2))
    echo "The sum is: $sum"
}

# Call the function
add_numbers 5 10
echo "The sum is: $sum"

-----------------------------------------------------------------------------

#!/bin/bash
# A function to check if a file exists

check_file() {
    local file_name=$1
    if [ -e "$file_name" ]; then
        echo "File $file_name exists."
    else
        echo "File $file_name does not exist."
    fi
}

# Call the function
check_file "test.txt" 


------------------------------------
#!/bin/bash
# A function to check if a user exists on the system

user_exists() {
    local username=$1
    if id "$username" &>/dev/null; then
        echo "User $username exists."
    else
        echo "User $username does not exist."
    fi
}

# Call the function
user_exists "root" 
user_exists "nonexistent_user"
user_exists "ec2-user"
----------------------------------------------------------------------

#!/bin/bash
# A function to print a multiplication table for a given number

multiplication_table() {
    local num=$1
    for i in {1..10}
    do
        echo "$num x $i = $((num * i))"
    done
}

# Call the function
multiplication_table 5
--------------------------------------------------------------------------------

#!/bin/bash
# A function to print all elements of an array

print_array() {
    local arr=("$@")
    echo "Array elements are:"
    for element in "${arr[@]}"; do
        echo "$element"
    done
}

# Call the function
my_array=("apple" "banana" "cherry")
----------------------------------------------------
Function with Arrays: Printing Array Elements 

#!/bin/bash
# A function to print all elements of an array

print_array() {
    local arr=("$@")
    echo "Array elements are:"
    for element in "${arr[@]}"; do
        echo "$element"
    done
}

# Call the function
my_array=("apple" "banana" "cherry")
print_array "${my_array[@]}"
------------------------------------------------------------------- 

