#!/bin/bash
# Script to reverse a given word

read -p "Enter a word: " word # Example input: "devops"

# Get the length of the word
length=${#word} # 6 

# Initialize an empty string for the reversed word
reversed=""

# Loop through the word from the last character to the first
for (( i=$length-1; i>=0; i-- ))  #for(i=6-1; i>=0; i-- ))
do
    reversed="$reversed${word:$i:1}" #spoved 
done
echo "Reversed word: $reversed"
# rev -It will automatically reverse the string


---------------------------------------------------------------------------- 
#!/bin/bash
# Script to count the number of words in a file, excluding extra spaces and empty lines

# Check if a filename is provided as an argument
if [ $# -eq 0 ]; then
    echo "Usage: $0 filename"
    exit 1
fi

filename="$1"

# Check if the file exists
if [ ! -f "$filename" ]; then
    echo "File not found!"
    exit 1
fi
--------------------------------------------------------------------------------------------------
# Count the number of words, excluding extra spaces and empty lines
word_count=$(tr -s ' ' '\n' < "$filename" | grep -v '^$' | wc -l)

# Output the result
echo "Number of words in the file '$filename': $word_count"
-----------------------------------------------------------------------------------------------------------

#!/bin/bash

trap "echo 'Ctrl+C detected. Exiting...'; exit 1" SIGINT

while true; do
  echo "Running... Press Ctrl+C to stop."
  sleep 2
done
-----------------------------------------------------

trap "echo 'Cannot terminate with SIGTERM'" SIGTERM

while true; do
  sleep 1
done
-----------------------------------------------------

