---
# Purpose: Showcase Jinja2 filters and methods for string manipulation.
# Key concepts: upper, lower, title, replace; ansible-lint and syntax check notes.
- name: This Playbook helps us to learn methods and filters
  hosts: localhost
  gather_facts: false
  vars:
    x: pramOth
  tasks:
    - name: Demo of filter and methods
      ansible.builtin.debug:
        msg:
          - "The value of x in upper case is {{ x | upper }}" # upper() --> uppercase
          - "The value of x in lower case is {{ x | lower }}"
          - "The value of x in title case is {{ x | title }}"
          - "The value of x in title case is {{ x | title() }}"  # Python ()
          - "The value of x with replaced 'O' to '0' is {{ x | replace('O', '0') }}"

# --syntax-check -- it will check for syntax Errors in your playbook 
# ansible lint to check the syntax and best partice it shows 
# Pip module --> sudo yum install pip 
# pip install ansible-lint 

