---
# Purpose: Demonstrate membership operator 'in' with lists and vars_prompt.
# Key concepts: vars_prompt, membership test in when, debug message.
- name: Check if a user is in a list
  hosts: localhost
  vars:
    users:
      - alice
      - bob
      - charlie
  vars_prompt:
    - name: check_user
      prompt: Enter the user to check 
      private: no 
  tasks:
    - name: Check if user is in the list
      ansible.builtin.debug:
        msg: "mentioned user is in the list of users {{ users }}"
      when: check_user in users


#  Used to test / valdatie the given data is exist or not {In and Not in}