---
- name: Check if a user is in a list
  hosts: localhost
  vars:
    users:
      - alice
      - bob
      - charlie
  tasks:
    - name: Check if user is in the list
      ansible.builtin.debug:
        msg: "mentioned user is in the list of users {{ users }}"
      when: "'pramoth' in users "


#  Used to test / valdatie the given data is exist or not {In and Not in}