---
- name: Using logical operators inside Jinja2 templates
  hosts: localhost
  vars:
    server_status: "healthy"
    cpu_usage: 75
    disk_space: 40
    service_status: "running"
    user_role: "admin"
    user_permissions: ["read", "write", "execute"]
    maintenance_mode: true 
    critical_users: ["alice", "bob", "charlie"]

  tasks:
    # Task 1: Server Health Check and CPU Optimization
    - name: Server Health Check and CPU Optimization
      debug:
        msg: "{{ 'Server is healthy and CPU usage is below 80.' if server_status == 'healthy' and cpu_usage < 80 else 'Condition not met.' }}"

    # Task 2: Service and Maintenance Status Evaluation
    - name: Service and Maintenance Status Evaluation
      debug:
        msg: "{{ 'Service is running or in maintenance mode.' if service_status == 'running' or maintenance_mode else 'Neither service is running nor in maintenance mode.' }}"

    # Task 3: Maintenance Mode Check
    - name: Maintenance Mode Check
      debug:
        msg: "{{ 'The server is not in maintenance mode.' if not maintenance_mode else 'The server is in maintenance mode.' }}"

    # Task 4: User Role Validation
    - name: User Role Validation
      debug:
        msg: "{{ 'User is admin.' if user_role == 'admin' else 'User is not admin.' }}"

    # Task 5: Disk Space Validation
    - name: Disk Space Validation
      debug:
        msg: "{{ 'Disk space is not 30%.' if disk_space != 30 else 'Disk space is 30%.' }}"

    # Task 6: Server Health and Disk Space Check
    - name: Server Health and Disk Space Check
      debug:
        msg: "{{ 'Server is healthy and CPU is below 80 or disk space is sufficient.' if (server_status == 'healthy' and cpu_usage < 80) or disk_space > 50 else 'Condition not met.' }}"

    # Task 7: Permission and Maintenance Status Check
    - name: Permission and Maintenance Status Check
      debug:
        msg: "{{ 'User is admin, has execute permission, and maintenance mode is off.' if user_role == 'admin' and 'execute' in user_permissions and not maintenance_mode else 'Condition not met.' }}"

    # Task 8: User Role and Guest Status Check
    - name: User Role and Guest Status Check
      debug:
        msg: "{{ 'User is admin or not a guest.' if user_role == 'admin' or user_role != 'guest' else 'User is a guest.' }}"

    # Task 9: Critical Users List Check
    - name: Critical Users List Check
      debug:
        msg: "{{ 'User is not in the critical users list.' if user_role not in critical_users else 'User is in the critical users list.' }}"

    # Task 10: Admin and Permission Validation
    - name: Admin and Permission Validation
      debug:
        msg: "{{ 'User is admin and has write permission.' if user_role == 'admin' and 'write' in user_permissions else 'Condition not met.' }}"


# and: Combines conditions. Returns True if both conditions are true.

# or: Combines conditions. Returns True if at least one condition is true.

# not: Inverts the condition. Returns True if the condition is false.

# ==: Checks for equality.

# !=: Checks for inequality.