---
  - name: Install playbook based on Os family
    hosts: all 
    gather_facts: false
    become: true
    tasks:
      - name: Installing a s/w 
        ansible.builtin.yum:
          name: nginx
          state: present
          update_cache: true

        

           
