---
  - name: Install playbook based on Os family
    hosts: all 
    gather_facts: true
    become: true
    tasks:
      - name: Prining the ansible_facts
        ansible.builtin.debug:
          msg: "{{ ansible_facts }}" 