---
  - name: Install playbook based on Os family
    hosts: all 
    gather_facts: true
    become: true
    vars_prompt:
      - name: software
        prompt: enter a software name to
    tasks:
      - name : This Play will help you to run in Linux
        ansible.builtin.yum:
          name: nginx
          state: present
          update_cache: yes
        when: ansible_facts.os_family == "RedHat"
      - name : This play will help you yo run in ubuntu
        ansible.builtin.apt:
          name: nginx
          state: present
          update_cache: true
        when: ansible_facts.os_family == "Debian"