---
  - name: Install playbook based on Os family
    hosts: all 
    gather_facts: true
    become: true
    tasks:
      - name: Installing s/w in Linux 
        ansible.builtin.yum:
          name: nginx
          state: present
        when: ansible_facts.os_family == "RedHat"
      - name: Installing s/w in ubuntu
        ansible.builtin.apt:
          name: nginx
          state: present
        when: ansible_facts.os_family == "Debian"