---
- name: This playbook shows demo on string operations 
  hosts: local 
  gather_facts: false
  vars:
    mydict: 
      linux: httpd
      ubuntu: apache2 
      linux.service: apache2
  tasks:
    - name: String operations
      ansible.builtin.debug:
        msg:
          - "{{ mydict }}"
          - "{{ mydict.keys() }}"
          - "{{ mydict.values() }}"
          - "{{ mydict.get('linux') }}"
    - name: Get the value of linux.service
      ansible.builtin.debug:
        msg: "{{ mydict.get('linux.service') }}"
    - name: Get the value of linux.service directly
      ansible.builtin.debug:
        msg: "{{ mydict['linux.service'] }}"




