---
# Purpose: Demonstrate when condition with file existence check.
# Key concepts: when, file test, debug message.
- name: Simple play with when conditional statement
  hosts: local
  become: true
  gather_facts: false
  vars:
    myFile: /etc/passwd
  tasks:
    - name: Displaying file name using debug module
      ansible.builtin.debug:
        msg:
          - "The file is: {{myFile}}"
  when: myFile is file
