---
- name: Simple play with when conditional statement
  hosts: local
  become: true
  gather_facts: false
  vars:
    myFile: /etc/passwd
  gather_facts: false 
  tasks:
    - name: Displaying file name using debug module
      ansible.builtin.debug:
        msg:
          - "The file is: {{myFile}}"
      when: myFile is exists
