---
# Purpose: Install per-distro package names passed via nested extra-vars.
# Key concepts: dict extra-vars, ansible_facts.pkg_mgr, conditional tasks.
- name: Play to install a given pkg based on pkg_mgr
  hosts: dev
  gather_facts: true
  become: yes
  tasks: 
    - name: Installing Pkgs using yum
      ansible.builtin.yum:
        name: "{{reqPkg.yum}}"
        state: present
        update_cache: yes
      when: ansible_facts.pkg_mgr == "yum"
    - name: Installing Pkgs using dnf 
      ansible.builtin.dnf:
        name: "{{reqPkg.dnf}}"
        state: present
        update_cache: yes
      when: ansible_facts.pkg_mgr == "dnf"
    - name: Installing Pkgs using apt
      ansible.builtin.apt:
        name: "{{reqPkg.apt}}"
        state: present
        update_cache: yes
      when: ansible_facts.pkg_mgr == "apt"            

# ansible-playbook <yaml> -e '{"reqPkg": {"yum": "httpd", "dnf": "nginx", "apt": "apache2"}}'
