---
# Purpose: Demonstrate handlers triggered via notify after a task change.
# Key concepts: notify/handlers, service start after package install, idempotency.
- name: Play to install nginx and then to start it 
  hosts: local
  gather_facts: false 
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx 
        state: present 
      notify:  Start nginx
    - name: Print uname value
      ansible.builtin.debug: 
        msg : " hi "
  handlers:
    - name: Start nginx
      ansible.builtin.service:
        name: nginx 
        state: started

