---
- name: Demo Playbook for Error Handling
  hosts: localhost
  gather_facts: false
  tasks:

    - name:  Run a command that may fail (nginx version)
      ansible.builtin.command:
        cmd: nginx -v
      register: nginx_result
      ignore_errors: true
    - name : Printing version
      ansible.builtin.debug:
        msg: "{{ nginx_result }}"
    - name:  Conditionally fail if nginx command succeeds
      ansible.builtin.debug:
        msg: "Nginx command succeeded unexpectedly!"
      when: nginx_result.rc == 0
      failed_when: nginx_result.rc == 0

    - name:  Run a safe command only if nginx failed
      ansible.builtin.command:
        cmd: uname
      when: nginx_result.rc != 0
      register: uname_output

    - name: Show uname output
      ansible.builtin.debug:
        msg: "Uname output: {{ uname_output.stdout }}"
      when: uname_output is defined
