---
- name: Setting JAVA_HOME 
  hosts: test 
  gather_facts: false
  become: yes

  vars: 
    reqLoc: /opt 
    targzFileName: "{{ (url | split('/'))[-1] }}" 
    reqJavaVer: "{{ ((targzFileName | split('_'))[0] | split('-'))[-1] }}"
    javaHomePath: "{{ reqLoc }}/jdk-{{ reqJavaVer }}"  
    targzFileNamePath: "{{ reqLoc }}/{{ targzFileName }}" 

  tasks:

    - name: Printing the values
      ansible.builtin.debug: 
        msg: 
          - "{{ reqLoc }}"
          - "{{ targzFileName }}"
          - "{{ reqJavaVer }}"
          - "{{ javaHomePath }}"
          - "{{ targzFileNamePath }}"

    - name: Downloading required tar.gz file 
      ansible.builtin.get_url:
        url: "{{ url }}"
        dest: "{{ targzFileNamePath }}"

    - name: Extracting tar.gz file 
      ansible.builtin.unarchive:
        src: "{{ targzFileNamePath }}"
        dest: "{{ reqLoc }}"
        remote_src: true

    - name: Removing old JAVA_HOME 
      ansible.builtin.lineinfile:
        path: /etc/environment 
        regex: "export JAVA_HOME"
        state: absent 

    - name: Setting JAVA_HOME ENV Variable 
      ansible.builtin.lineinfile:
        path: /etc/environment 
        line: "export JAVA_HOME={{ javaHomePath }}"
        state: present

    - name: Removing tar.gz file 
      ansible.builtin.file: 
        path: "{{ targzFileNamePath }}"
        state: absent

# # https://download.java.net/java/GA/jdk18.0.2/f6ad4b4450fd4d298113270ec84f30ee/9/GPL/openjdk-18.0.2_linux-x64_bin.tar.gz
# # https://download.java.net/java/GA/jdk19.0.1/afdd2e245b014143b62ccb916125e3ce/10/GPL/openjdk-19.0.1_linux-x64_bin.tar.gz
# # https://download.java.net/java/early_access/jdk26/8/GPL/openjdk-26-ea+8_linux-x64_bin.tar.gz
# # https://download.java.net/java/early_access/jdk25/33/GPL/openjdk-25-ea+33_linux-x64_bin.tar.gz

# https://download.oracle.com/java/21/latest/jdk-21_linux-aarch64_bin.tar.gz 


# Loops: 
# Valut
# dynamic inventory
# scerts: 
# ansible.builtin.template  
