---
# Purpose: Show usage of lists and dictionaries in vars and how to access items.
# Key concepts: list indexing, dict key access, ansible.builtin.debug, Jinja2 indexing.
- name: Variable with List & Dict
  hosts: localhost
  gather_facts: false
  vars:
    myvalue: 5
    mylist: #[10,15,20] ---> index is start Zero 0 or you can use -1,-2 
      - 15
      - 10
      - "ansible"
    myDict:  # Key: value pair 
      myfirst: 5
      mysecond: " this is devops class "

  tasks:
    - name: Printing the values
      ansible.builtin.debug:
        msg: "{{ myvalue }} {{ mylist }} {{ myDict }}"

    - name: Printing the index value from list
      ansible.builtin.debug:
        msg: 
          - "{{ mylist[1] }}"
          - "{{ mylist[-1] }}"

    - name: Printing a specific Dictionary value
      ansible.builtin.debug:
        msg: "{{ myDict.mysecond }}"
