---
- name: This playbook defines how will you use vars_file to print varibales 
  hosts: local
  gather_facts: false
  vars_files:
    - varswithjson.json
    - varswithyaml.yaml
  tasks:
      - name : Printing value from json value
        ansible.builtin.debug:
          msg: 
            - " this is print value in json values "
            - "{{myvar}} {{ mylist }} {{ mydict }}"
      - name : Printing value from yaml value
        ansible.builtin.debug:
          msg: 
            - " this is print value in json values "
            - "{{ myvaryaml }} {{ mylistyaml }} {{ mydictyaml }}"