---
# Purpose: Demonstrate overriding vars via command line extra-vars (-e).
# Key concepts: variable precedence, CLI -e/--extra-vars, ansible.builtin.debug.
- name: Passing values from the command line 
  hosts: local
  gather_facts: false
  vars:
    x: 15 # it will overide if pass value in Command line 
  tasks:
      - name : Gettin the value of x from running playbook
        ansible.builtin.debug:
            msg: "the value of x is {{ x }}"

# to pass the value during runtime you have use option -e or --extra-vars "x=10"

#Top -- Command line Pirority  
