---
- name : Passing values from the command line 
  hosts: local
  gather_facts: true 
  tasks:
      - name : Gettin the value of x from running playbook
        ansible.builtin.debug:
            msg: "the value of x is {{ x }}"