---
- name: Getting input from the user
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: x
      prompt: "Enter the value of x"
      private: no  # Optional: ensures the input is not hidden

  tasks:
    - name: Printing the value of x
      ansible.builtin.debug:
          msg: "The value of x is {{ x }}"
