---
# Purpose: Capture command outputs using register and reference stdout/stderr.
# Key concepts: ansible.builtin.command, register var, stdout vs stderr, debugging.
- name : Registering the output
  hosts: local
  gather_facts: false 
  tasks: 
      - name: Getting the Uname value
        ansible.builtin.command: "uname"
        register: unameout
      - name: Printing the uname value 
        ansible.builtin.debug:
          msg: " {{ unameout.stdout }}"
      - name: Need to get the version for Nginx
        ansible.builtin.command: "nginx -v"
        register: temp
      - name: Displaying the nginx version
        ansible.builtin.debug:
            msg: "{{ temp.stderr }}"