---
- name : Registering the output
  hosts: local
  gather_facts: false 
  tasks: 
      - name: Getting the Uname value
        ansible.builtin.command: "uname"
        register: unameout
      - name: Printing the uname value 
        ansible.builtin.debug:
          msg: " {{ unameout }}"