---
- name : Registering the output
  hosts: local
  gather_facts: false 
  tasks: 
      - name: Getting the Uname value
        ansible.builtin.command: "uname"
        register: output
      - name: printing the ouput
        ansible.builtin.debug:
          msg: " the value of uname is {{ output.stdout }}"
      - name: Getting nginx version
        ansible.builtin.command: " nginx -version"
        register: version
      - name : Printing the Nginx version 
        ansible.builtin.debug:
          msg: " {{ version }}"