---
  - name: Demo for show facts 
    hosts: local
    gather_facts: false
    vars: 
      - x: 10
      - y: 15 
    tasks: 
        - name: Printing the vars value
          ansible.builtin.debug:
            msg: 
            - " the value of x is {{ x }}"
            - " the value of y is {{ y }}"
        - name: We will be changing the value of x
          ansibile.builtin.setfacts:
            - x: 150
            - y: 205
         - name: Printing the change value
           ansible.builtin.debug:
            msg: 
            - " the value of x is {{ x }}"
            - " the value of y is {{ y }}"
