- name: Install apache2 on Debian
  ansible.builtin.package:
    name: apache2
    state: present

- name: Start apache2
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
  tags: start