- name: install nginx s/w
  hosts: all
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.package:
          name: nginx
          state: present
    - name: start nginx service
      ansible.builtin.systemd:
          name: nginx
          state: started
          enabled: true 